#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

# Run lint and prettier check before commit
npm run lint
if [ $? -ne 0 ]; then
  echo "\n❌ Lint errors found. Commit aborted."
  exit 1
fi

npm run prettier-check
if [ $? -ne 0 ]; then
  echo "\n❌ Prettier check failed. Commit aborted."
  exit 1
fi

echo "\n✅ Lint and Prettier checks passed. Proceeding with commit."
